steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$SERVICE_NAME', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$SERVICE_NAME']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '$SERVICE_NAME',
      '--image', 'gcr.io/$PROJECT_ID/$SERVICE_NAME',
      '--region', '$DEPLOY_REGION',
      '--platform', '$PLATFORM',
      '--allow-unauthenticated'
    ]

# Specify the service account to use for the build
service_account: '963201605868-compute@developer.gserviceaccount.com'

# Use Cloud Logging only (no logs bucket required)
options:
  logging: 'CLOUD_LOGGING_ONLY'

# Set build timeout (optional)
timeout: '900s'

# Specify substitutions for your variables
substitutions:
  _DEPLOY_REGION: 'us-central1'
  _PLATFORM: 'managed'
  _SERVICE_NAME: 'identify-face-app'
  _PROJECT_ID: 'face-recognition-438311'
