name: Build and deploy container app to GCP Cloud Run - facerecognition

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_APP_CREDENTIALS }}

    - name: Build and push container image to Google Container Registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/facerecognition:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_APP_CREDENTIALS }}
        service_account_key: ${{ secrets.GCP_APP_CREDENTIALS }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy facerecognition \
        --image gcr.io/${{ secrets.GCP_APP_CREDENTIALS }}/facerecognition:${{ github.sha }} \
        --platform managed \
        --region ${{ secrets.GCP_APP_CREDENTIALS }} \
        --allow-unauthenticated
