#name: Deploy to Cloud Run
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  dockerize-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Google Cloud Auth
#        uses: 'google-github-actions/auth@v2'
#        with:
#          credentials_json: '${{ secrets.GCP_APP_CREDENTIALS }}'
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#
#      - name: Set up Cloud SDK
#        uses: 'google-github-actions/setup-gcloud@v2'
#
#      - name: Configure Docker
#        run: |
#          gcloud auth configure-docker us-central1-docker.pkg.dev
##          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
#
#      - name: Build and Push Docker Image
#        run: |
#          docker build -t ${{ secrets.GCP_IMAGE_URL }}:latest .
#          docker push ${{ secrets.GCP_IMAGE_URL }}:latest
#
#      - name: Deploy to Cloud Run
#        run: |
#          gcloud run deploy face-recognition \
#            --image ${{ secrets.GCP_IMAGE_URL }}:latest \
#            --platform managed \
#            --region us-central1 \
#            --allow-unauthenticated
#
#
## gcloud run deploy --image=us-central1-docker.pkg.dev/face-recognition-438311/face-recognition-docker-repo/face-recognition-image:tag1

name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'face-recognition-438311'
  NAME: 'face-recognition-docker-repo'
  REGION: 'us-central1'
  SERVICE: 'face-recognition-app'
  LOCATION: 'us-central1'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'


      -  name: 'Authenticate to Google Cloud'
         id: 'auth'
         uses: 'google-github-actions/auth@v2'
         with:
          credentials_json: '${{ secrets.GCP_APP_CREDENTIALS }}'

      -  name: 'Docker Auth'
         run: |-
           gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev"

      - name: 'Build and Push Container'
        run: |-
          docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.NAME }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.NAME }}/${{ env.SERVICE }}:${{ github.sha }}"

      # - name: 'Deploy to Cloud Run'
      #   id: deploy
      #   uses: 'google-github-actions/deploy-cloudrun@v2'
      #   with:
      #     service: '${{ env.SERVICE }}'
      #     region: '${{ env.REGION }}'
      #     image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
      #     port: 8000
      -  name: 'Deploy to Cloud Run'
         run:  |
           gcloud run deploy face-recognition-app \
            --image "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.NAME }}/${{ env.SERVICE }}:${{ github.sha }}" \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}