# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - facerecognitionregistry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://facerecognitionregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0cf649ba70fd4b278207c5da89ed33eb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_507516c31b4a47ff98d42de0d3fff0d7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: facerecognitionregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0cf649ba70fd4b278207c5da89ed33eb }}/project:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'facerecognitionregistry'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4f6dbb801350422a9c9861a5b12c5890 }}
        images: 'facerecognitionregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0cf649ba70fd4b278207c5da89ed33eb }}/project:${{ github.sha }}'